[project]
name = "ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dash>=3.0.3",
    "gunicorn>=23.0.0",
    "langchain-community>=0.3.23",
    "langchain[openai]>=0.3.25",
]
